//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgtechYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveRequests
    {
        public int ActiveRequestID { get; set; }
        public int RequestID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> RepairPartsID { get; set; }
        public Nullable<int> MasterID { get; set; }
    
        public virtual RepairRequests RepairRequests { get; set; }
        public virtual RepairParts RepairParts { get; set; }
        public virtual Users Users { get; set; }
    }
}
